### ISSUE TITLE
Configs of Distilling to a Lightweight Backbone.

### ISSUE THREAD

**Issue by 0russ** [ChenhongyiYang/PGD#2]
Hello, thanks for sharing your excellent work on detection distillation! 
I am very impressed with your paper and I found that your distillation method achieves outstanding performance on the lightweight backbone. I wonder if you can provide the training config of distilling to a lightweight backbone, thanks a lot!

![image](https://user-images.githubusercontent.com/54385993/167237541-dbda5067-128a-4765-aa15-12312f226e4e.png)

**Comment by ChenhongyiYang** [comment]
Hello. Thank you for trying our code. We have updated the configs for MobileNetv2. 

Please check: [pgd_atss_r101_mb2_1x.py](https://github.com/ChenhongyiYang/PGD/blob/main/work_configs/pgd_atss_r101_mb2_1x.py)

**Comment by 0russ** [comment]
> Hello. Thank you for trying our code. We have updated the configs for MobileNetv2.
> 
> Please check: [pgd_atss_r101_mb2_1x.py](https://github.com/ChenhongyiYang/PGD/blob/main/work_configs/pgd_atss_r101_mb2_1x.py)

Thanks for your reply! But I still have two questions:
1. mbv2 student and r101 teacher have different in_channel numbers at FPN, how do you handle this situation?
2. Is the distillation setting for fcos_mbv2 the same as atss_mbv2, could you please update its training config as well?
