### ISSUE TITLE
two questions about the configs for MobileNetv2.

### ISSUE THREAD

**Issue by 0russ** [ChenhongyiYang/PGD#3]
> Hello. Thank you for trying our code. We have updated the configs for MobileNetv2.
> 
> Please check: [pgd_atss_r101_mb2_1x.py](https://github.com/ChenhongyiYang/PGD/blob/main/work_configs/pgd_atss_r101_mb2_1x.py)

Thanks for your reply! But I still have two questions:
1. mbv2 student and r101 teacher have different in_channel numbers at FPN, how do you handle this situation?
2. Is the distillation setting for fcos_mbv2 the same as atss_mbv2, could you please update its training config as well?

_Originally posted by @0russ in https://github.com/ChenhongyiYang/PGD/issues/2#issuecomment-1120590935_

**Comment by ChenhongyiYang** [comment]
Hello, sorry for the late reply.

- FPN: The lateral connections are initialized from scratch because of channel difference. The fusion layers are initialized from the teacher checkpoint because both student and teacher have 256 channels. 
- Mobile v2 FCOS: The config is added.

Thank you :-)
